Fix num/denom distortion for first round of assignments when clustering
datastax/jvector pull request #121
Opened 2023-10-09 19:40 UTC by jkni

The old assignments on first run do not have any value, but they lie in the valid space of assignments (centroid 0), so centroid 0 gets distorted during the first round of assignment. This PR also includes a test that exposes this issue and exercises a surprising amount of the interesting bits of PQ/KMPP.

2023-10-10 21:46 UTC, jbellis requested changes

2023-10-10 21:46 UTC, jbellis commented on jvector-base/src/main/java/io/github/jbellis/jvector/pq/KMeansPlusPlusClusterer.java
> +            var oldAssignment = firstRun ? -1 : assignments[i];
could we get rid of the firstRun flag and the if statements by just calling Arrays.fill(assignments, -1) to start with?

2023-10-10 21:49 UTC, jbellis requested changes

2023-10-10 21:49 UTC, jbellis commented on jvector-base/src/main/java/io/github/jbellis/jvector/pq/KMeansPlusPlusClusterer.java
> +    private int assignPointsToClusters(boolean firstRun) {
i don't love "flag parameters" that change behavior, could we split this into assignInitialPoints and assignIteratedPoints (names subject to change)?

2023-10-11 15:02 UTC, jkni commented on jvector-base/src/main/java/io/github/jbellis/jvector/pq/KMeansPlusPlusClusterer.java
> +    private int assignPointsToClusters(boolean firstRun) {
Sure, I went back-and-forth on exactly this and didn't have strong feelings. Pushing an update.

2023-10-11 17:01 UTC, jbellis approved these changes

2023-10-11 17:25 UTC, merged